# Generated by Django 2.2.7 on 2019-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
